image: maven:latest

stages:
  - compile
  - package

compile:
  stage: test
  script:
    - ls
    - mvn compile
    - ls
  artifacts:
    paths:
      - target

package:
  stage: package
  script:
    - ls
    - mvn package