image: maven:latest

stages:
  - package

package first:
  stage: package
  script:
    - mvn package
  rules:
    - changes:
        - gitlab-ci-mm-first/**

package second:
  stage: package
  script:
    - mvn package
  rules:
    - changes:
        - gitlab-ci-mm-second/**